openapi: 3.0.0
info:
  title: HydroAPI
  version: 1.0.0
  description: API for managig the hydroponics' systems

servers:
  - url: http://localhost:8000
    description: Currently local server

paths:
  /api/auth/register/:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object

  /api/auth/login/:
    post:
      summary: Authenticate a user and return a token
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object

        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
